export const MARKETING_ASSET_SEEDS = [
  {
    title: "Focused student at work",
    category: "Learning and education",
    niche: "Education",
    source: "https://www.pexels.com/video/student-studying-on-laptop-and-notebook-indoors-30592298/",
    tags: ["study", "focus", "laptop"],
  },
  {
    title: "Collaborative online learning",
    category: "Student success",
    niche: "Education",
    source: "https://www.pexels.com/video/students-using-laptops-7777997/",
    tags: ["students", "collaboration", "learning"],
  },
  {
    title: "Learning from home",
    category: "Digital skills",
    niche: "Online courses",
    source: "https://www.pexels.com/video/student-using-his-laptop-6985335/",
    tags: ["online class", "home", "skills"],
  },
  {
    title: "Productive cafe founder",
    category: "Young entrepreneur",
    niche: "Business",
    source: "https://www.pexels.com/video/businessman-working-using-laptop-9613997/",
    tags: ["founder", "cafe", "laptop"],
  },
  {
    title: "Campus study team",
    category: "Student success",
    niche: "Education",
    source: "https://www.pexels.com/video/a-group-of-students-studying-6145947/",
    tags: ["campus", "team", "progress"],
  },
  {
    title: "Executive digital workflow",
    category: "Business coaching",
    niche: "Consulting",
    source: "https://www.pexels.com/video/businessman-working-using-laptop-8939325/",
    tags: ["executive", "office", "strategy"],
  },
  {
    title: "Classroom collaboration",
    category: "Learning and education",
    niche: "Teaching",
    source: "https://www.pexels.com/video/students-working-on-a-laptop-in-a-classroom-5200028/",
    tags: ["classroom", "teamwork", "technology"],
  },
  {
    title: "Professional project momentum",
    category: "Online business",
    niche: "Freelancing",
    source: "https://www.pexels.com/video/businessman-working-on-a-laptop-8425705/",
    tags: ["project", "professional", "work"],
  },
  {
    title: "Focused home office",
    category: "Freelancing",
    niche: "Services",
    source: "https://www.pexels.com/video/a-businessman-using-a-laptop-while-working-8124015/",
    tags: ["remote work", "focus", "service"],
  },
  {
    title: "Lifelong digital learning",
    category: "Motivation",
    niche: "Education",
    source: "https://www.pexels.com/video/a-man-studying-using-his-laptop-5762416/",
    tags: ["growth", "learning", "motivation"],
  },
  {
    title: "Content planning desk",
    category: "Creator studio",
    niche: "Content creation",
    source: "https://www.pexels.com/video/student-studying-with-notebook-and-supplies-36326871/",
    tags: ["planning", "notes", "content"],
  },
  {
    title: "Laptop business montage",
    category: "Laptop work",
    niche: "Online business",
    source: "https://www.pexels.com/search/videos/Entrepreneur%20working%20on%20a%20laptop/",
    tags: ["laptop", "business", "entrepreneur"],
  },
].map((asset, index) => ({
  ...asset,
  description: "A licensed stock-video reference selected for creator marketing concepts and short-form campaign planning.",
  videoUrl: asset.source,
  thumbnailUrl: null,
  licenseType: "Pexels License — free to use; verify current source terms before campaign publication",
  duration: "Source clip",
  orientation: index % 3 === 0 ? "horizontal" : "vertical",
  isPremium: index >= 4,
  isActive: true,
  caption: {
    hook: [
      "The skill is not the problem. The way you present it might be.",
      "What if your next customer understood your value in ten seconds?",
      "You do not need more ideas. You need a clear offer.",
    ][index % 3],
    caption: "A professional online offer starts with one clear promise, a simple next step, and consistent proof that you understand the customer.",
    hashtags: "#OnlineBusiness #DigitalSkills #CreatorBusiness #BuildInPublic",
    cta: "See the full offer through the link.",
    voiceoverScript: "You already have something useful to teach or sell. Package it clearly, give it a professional home, and invite the right people to take one next step.",
  },
}));

export const MARKETING_STRATEGY_SEEDS = [
  {
    title: "Seven-Day Offer Launch",
    slug: "seven-day-offer-launch",
    category: "Launch strategy",
    description: "A focused one-week sequence that moves from problem awareness to a direct launch invitation.",
    steps: ["Define one specific customer outcome.", "Publish a problem-awareness post.", "Share your method or framework.", "Show proof or a useful demonstration.", "Handle the strongest objection.", "Open the offer with a direct CTA.", "Follow up with urgency and clarity."],
    bestPlatform: "Instagram + WhatsApp",
    difficultyLevel: "beginner",
    recommendedPageType: "all",
    isPremium: false,
  },
  {
    title: "WhatsApp Conversation Funnel",
    slug: "whatsapp-conversation-funnel",
    category: "WhatsApp selling strategy",
    description: "Turn status views and warm contacts into respectful sales conversations.",
    steps: ["Post a result-focused status.", "Invite replies with a simple question.", "Qualify the person before pitching.", "Send the most relevant page link.", "Follow up once with a specific benefit."],
    bestPlatform: "WhatsApp",
    difficultyLevel: "beginner",
    recommendedPageType: "service",
    isPremium: false,
  },
  {
    title: "Three-Pillar Personal Brand",
    slug: "three-pillar-personal-brand",
    category: "Personal brand strategy",
    description: "Build recognizable authority around expertise, perspective, and proof.",
    steps: ["Choose one expertise pillar.", "Choose one values or perspective pillar.", "Choose one proof and process pillar.", "Rotate the pillars across the week.", "Connect each pillar to the same offer."],
    bestPlatform: "Instagram",
    difficultyLevel: "beginner",
    recommendedPageType: "coaching-program",
    isPremium: false,
  },
  {
    title: "DM Closing Without Pressure",
    slug: "dm-closing-without-pressure",
    category: "DM closing strategy",
    description: "A practical question-led flow for understanding fit before making an offer.",
    steps: ["Ask what they are trying to achieve.", "Clarify what is blocking them.", "Reflect the gap in their words.", "Explain the relevant part of your offer.", "Invite a clear yes or no next step."],
    bestPlatform: "Instagram DM",
    difficultyLevel: "intermediate",
    recommendedPageType: "service",
    isPremium: true,
  },
  {
    title: "Short-Form Hook Matrix",
    slug: "short-form-hook-matrix",
    category: "TikTok short-form strategy",
    description: "Generate repeatable hooks from mistakes, outcomes, myths, and demonstrations.",
    steps: ["List five costly mistakes.", "List five desired outcomes.", "List five common myths.", "Record one direct hook for each.", "Use the page CTA in the final three seconds."],
    bestPlatform: "TikTok",
    difficultyLevel: "intermediate",
    recommendedPageType: "all",
    isPremium: true,
  },
  {
    title: "Trust Before Urgency",
    slug: "trust-before-urgency",
    category: "Trust-building strategy",
    description: "Establish credibility before introducing deadlines, scarcity, or limited capacity.",
    steps: ["Show how the offer works.", "Publish a real example.", "Explain who should not buy.", "Answer pricing concerns directly.", "Only then communicate a genuine deadline."],
    bestPlatform: "Instagram + Email",
    difficultyLevel: "intermediate",
    recommendedPageType: "all",
    isPremium: true,
  },
  {
    title: "Value-Based Pricing Story",
    slug: "value-based-pricing-story",
    category: "Pricing strategy",
    description: "Frame price around the cost of the problem and the value of the outcome.",
    steps: ["Name the current cost of the problem.", "Describe the desired result.", "Show what is included.", "Explain the support or speed advantage.", "Present the price without apology."],
    bestPlatform: "Landing page",
    difficultyLevel: "intermediate",
    recommendedPageType: "consultation",
    isPremium: true,
  },
  {
    title: "Local Market Proof Loop",
    slug: "local-market-proof-loop",
    category: "Local African market strategy",
    description: "Use locally relevant examples, channels, language, and customer proof to reduce uncertainty.",
    steps: ["Choose a familiar customer situation.", "Use local currency or practical comparisons.", "Feature proof from a recognizable context.", "Offer WhatsApp as a low-friction next step.", "Turn common questions into future posts."],
    bestPlatform: "WhatsApp + Facebook",
    difficultyLevel: "beginner",
    recommendedPageType: "all",
    isPremium: true,
  },
  {
    title: "Monthly Content Engine",
    slug: "monthly-content-engine",
    category: "Content calendar strategy",
    description: "Turn one offer into four repeatable weekly content themes.",
    steps: ["Week one: customer problems.", "Week two: your method.", "Week three: proof and stories.", "Week four: offer and objections.", "Repeat with new examples."],
    bestPlatform: "Multi-platform",
    difficultyLevel: "intermediate",
    recommendedPageType: "all",
    isPremium: true,
  },
  {
    title: "Offer Positioning Canvas",
    slug: "offer-positioning-canvas",
    category: "Offer positioning strategy",
    description: "Clarify the audience, painful gap, unique mechanism, result, and reason to act.",
    steps: ["Name one audience segment.", "Define the expensive or frustrating gap.", "Describe your distinct approach.", "State the measurable or emotional result.", "Write one sentence combining all four."],
    bestPlatform: "Landing page",
    difficultyLevel: "advanced",
    recommendedPageType: "all",
    isPremium: true,
  },
].map((strategy) => ({
  ...strategy,
  exampleCaptions: [
    "Your audience does not need every detail. They need to understand the problem, the result, and the next step.",
    "A clear offer feels easier to trust because the customer can quickly decide whether it fits.",
  ],
  examplePosts: [
    "Problem post: describe one expensive mistake and one practical correction.",
    "Proof post: show the process, result, or lesson behind a customer win.",
  ],
  recommendedCta: "Visit the page to see the full offer and take the next step.",
  isActive: true,
}));
